// <auto-generated />
using System;
using CK41Tours.DAO;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CK41Tours.Migrations
{
    [DbContext(typeof(CK41ToursDbContext))]
    [Migration("20241118120733_DD")]
    partial class DD
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CK41Tours.Models.DataModels.DDEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DD01")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DD02")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DD03")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DD04")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DD05")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DD06")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DD07")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DD08")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DD09")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DD10")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DD11")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ip")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsInActive")
                        .HasColumnType("bit");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Remark")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("DD");
                });

            modelBuilder.Entity("CK41Tours.Models.DataModels.DTEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DT01")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DT02")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DT03")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ip")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsInActive")
                        .HasColumnType("bit");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Remark")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("DT");
                });

            modelBuilder.Entity("CK41Tours.Models.DataModels.TGEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Ip")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsInActive")
                        .HasColumnType("bit");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Remark")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TG01")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TG02")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("TG");
                });

            modelBuilder.Entity("CK41Tours.Models.DataModels.TMEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Ip")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsInActive")
                        .HasColumnType("bit");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Remark")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TM01")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TM02")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TM03")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TM04")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TM05")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("TM");
                });

            modelBuilder.Entity("CK41Tours.Models.DataModels.TTEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Ip")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsInActive")
                        .HasColumnType("bit");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Remark")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TT01")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TT02")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TT03")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("TT");
                });
#pragma warning restore 612, 618
        }
    }
}
